// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Node struct {
	ID          int32
	ExecutionID uuid.NullUUID
	Name        sql.NullString
	Children    []int32
	Parents     []int32
	Inputs      []string
}

type QueueItem struct {
	ID        uuid.UUID
	Inputs    []string
	CreatedAt time.Time
}

type Result struct {
	ID      int32
	NodeID  int32
	Ts      sql.NullTime
	Stdout  sql.NullString
	Stderr  sql.NullString
	Skipped sql.NullBool
	Outputs []string
}

type Status struct {
	ID         int32
	NodeID     int32
	Ts         sql.NullTime
	ExternalID uuid.NullUUID
	Status     sql.NullString
	Submitted  time.Time
	Started    sql.NullTime
	Ended      sql.NullTime
}
