#!/bin/bash
shopt -s globstar

# Suppress tika error due to no hostname in container
echo 127.0.0.1 $HOSTNAME >> /etc/hosts

export DEFAULT_FILENAME=file
export APPEND_EXTENSION=metadata.json
# export DEBUG=true

# Run tika on all files in the input directory
# The \| is required so the eval doesn't interpret this as a pipe in the 'run_program.sh' command
# The tee is required to write the output to a file and stdout
run_program.sh 'java -jar /opt/tika-app.jar --json ${input_file} \| tee ${output_file}' /inputs /outputs  > /outputs/stdout

# Parse the output with jq and report on things we're interested in
cat /outputs/stdout | jq -M -c '. | {"Content-Type":."Content-Type","Content-Length":."Content-Length"}'
