workflow:
  disable_derivative: false # Disable the running of one final job to produce a derivative
# Job specs define the configuration for Bacalhau jobs
jobs:
- name: metadata # This is the key used when looking for a job
  image: ghcr.io/bacalhau-project/amplify/tika:latest@sha256:266a93a391f139e6d23cff2cd9e4b555e49a58f001c20e9082a62a6859a02a50
  entrypoint: ["extract-metadata", "/inputs", "/outputs"] # Container entrypoint
  inputs:
    path: /inputs # This is where the CID is placed in the Bacalhau job
  outputs:
    path: /outputs # This is where the result is placed in the Bacalhau job
- name: merge
  image: ubuntu
  entrypoint:
  - bash
  - -c
  - >-
    if [ -d /inputs ] ; then cp -r /inputs/* /outputs ; else cp /inputs /outputs/blob ; fi &&
    find / -iwholename '/inputs*metadata.json' | while read line ; do
    result=$(
    echo $line |
    sed 's/\(.*\)outputs\//\1/g' |
    sed 's/\/inputs[0-9]*//g' |
    sed -r 's/(.+)\//\1./g'
    ) ;
    output=/outputs${result} ;
    mkdir -p $(dirname ${output}) ;
    echo "Copying $line to $output" ;
    cp $line $output
    ; done
  inputs:
    path: /inputs
  outputs:
    path: /outputs
workflows:
- name: first
  jobs: # Defines order of jobs -- workflows run in order
  - name: metadata # Must match the name of a job
  - name: merge
- name: second
  jobs: # Defines order of jobs -- workflows run in order
  - name: metadata # Must match the name of a job
  - name: merge
# createSingleDerivative: true
# workflows:
# - name: parquet
#   jobs: # Defines order of jobs -- workflows run in order
#   - name: metadata # Must match the name of a job, is cached internally
#   - name: merge
#   - name: parquet
# - name: createACollage
#   jobs: 
#   - name: metadata 
#   - name: merge
#   - name: image-resize
#     runIfStdOutRegex: '"mime-type": "image/*"'
#   - name: collage
# - name: yolo
#   jobs: 
#   - name: metadata
#   - name: merge
#   - name: image-resize
#     runIfStdOutRegex: '"mime-type": "image/*"'
#   - name: yolo
