// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
)

// Error defines model for error.
type Error struct {
	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Title A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
	Title *string `json:"title,omitempty"`
}

// Errors defines model for errors.
type Errors = []Error

// ExecutionRequest defines model for executionRequest.
type ExecutionRequest struct {
	Cid string `json:"cid"`
}

// Graph defines model for graph.
type Graph struct {
	Data  *[]NodeConfig `json:"data,omitempty"`
	Links *Links        `json:"links,omitempty"`
}

// Home defines model for home.
type Home struct {
	Links *Links  `json:"links,omitempty"`
	Type  *string `json:"type,omitempty"`
}

// Item defines model for item.
type Item struct {
	Id       string       `json:"id"`
	Links    *Links       `json:"links,omitempty"`
	Metadata ItemMetadata `json:"metadata"`
	Type     string       `json:"type"`
}

// ItemMetadata defines model for itemMetadata.
type ItemMetadata struct {
	Ended     *string `json:"ended,omitempty"`
	Started   *string `json:"started,omitempty"`
	Status    string  `json:"status"`
	Submitted string  `json:"submitted"`
}

// Job defines model for job.
type Job struct {
	Entrypoint *[]string `json:"entrypoint,omitempty"`
	Id         string    `json:"id"`
	Image      string    `json:"image"`
	Links      *Links    `json:"links,omitempty"`
	Type       string    `json:"type"`
}

// Jobs defines model for jobs.
type Jobs struct {
	Data  *[]Job `json:"data,omitempty"`
	Links *Links `json:"links,omitempty"`
}

// Links defines model for links.
type Links = map[string]interface{}

// Node defines model for node.
type Node struct {
	Children *[]Node            `json:"children,omitempty"`
	Id       openapi_types.UUID `json:"id"`
	Inputs   []ExecutionRequest `json:"inputs"`
	Links    *Links             `json:"links,omitempty"`
	Metadata ItemMetadata       `json:"metadata"`
	Outputs  []ExecutionRequest `json:"outputs"`
	Status   *Status            `json:"status,omitempty"`
	Type     string             `json:"type"`
}

// NodeConfig Static configuration of a node.
type NodeConfig struct {
	Id      *string       `json:"id,omitempty"`
	Inputs  *[]NodeInput  `json:"inputs,omitempty"`
	JobId   *string       `json:"job_id,omitempty"`
	Outputs *[]NodeOutput `json:"outputs,omitempty"`
}

// NodeInput Input specification for a node.
type NodeInput struct {
	OutputId  *string `json:"output_id,omitempty"`
	Path      *string `json:"path,omitempty"`
	Predicate *string `json:"predicate,omitempty"`
	Root      *bool   `json:"root,omitempty"`
	StepId    *string `json:"step_id,omitempty"`
}

// NodeOutput Output specification for a node.
type NodeOutput struct {
	Id   *string `json:"id,omitempty"`
	Path *string `json:"path,omitempty"`
}

// Queue defines model for queue.
type Queue struct {
	Data  *[]Item `json:"data,omitempty"`
	Links *Links  `json:"links,omitempty"`
}

// Status defines model for status.
type Status struct {
	// Id External execution ID
	Id *string `json:"id,omitempty"`

	// Skipped Whether this node was skipped due to predicates not matching.
	Skipped *bool `json:"skipped,omitempty"`

	// Status External status of the job
	Status *string `json:"status,omitempty"`
	Stderr *string `json:"stderr,omitempty"`
	Stdout *string `json:"stdout,omitempty"`
}

// PostApiV0QueueFormdataRequestBody defines body for PostApiV0Queue for application/x-www-form-urlencoded ContentType.
type PostApiV0QueueFormdataRequestBody = ExecutionRequest

// PutApiV0QueueIdJSONRequestBody defines body for PutApiV0QueueId for application/json ContentType.
type PutApiV0QueueIdJSONRequestBody = ExecutionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Amplify Home
	// (GET /)
	Get(w http.ResponseWriter, r *http.Request)
	// Amplify V0 API Home
	// (GET /api/v0)
	GetApiV0(w http.ResponseWriter, r *http.Request)
	// Get Amplify work graph
	// (GET /api/v0/graph)
	GetApiV0Graph(w http.ResponseWriter, r *http.Request)
	// List all Amplify jobs
	// (GET /api/v0/jobs)
	GetApiV0Jobs(w http.ResponseWriter, r *http.Request)
	// Get a job by id
	// (GET /api/v0/jobs/{id})
	GetApiV0JobsId(w http.ResponseWriter, r *http.Request, id string)
	// Amplify work queue
	// (GET /api/v0/queue)
	GetApiV0Queue(w http.ResponseWriter, r *http.Request)
	// Run all workflows for a CID (not recommended)
	// (POST /api/v0/queue)
	PostApiV0Queue(w http.ResponseWriter, r *http.Request)
	// Get an item from the queue by id
	// (GET /api/v0/queue/{id})
	GetApiV0QueueId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Run all workflows for a CID
	// (PUT /api/v0/queue/{id})
	PutApiV0QueueId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// Get operation middleware
func (siw *ServerInterfaceWrapper) Get(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Get(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetApiV0 operation middleware
func (siw *ServerInterfaceWrapper) GetApiV0(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV0(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetApiV0Graph operation middleware
func (siw *ServerInterfaceWrapper) GetApiV0Graph(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV0Graph(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetApiV0Jobs operation middleware
func (siw *ServerInterfaceWrapper) GetApiV0Jobs(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV0Jobs(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetApiV0JobsId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV0JobsId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", mux.Vars(r)["id"], &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV0JobsId(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetApiV0Queue operation middleware
func (siw *ServerInterfaceWrapper) GetApiV0Queue(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV0Queue(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostApiV0Queue operation middleware
func (siw *ServerInterfaceWrapper) PostApiV0Queue(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV0Queue(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetApiV0QueueId operation middleware
func (siw *ServerInterfaceWrapper) GetApiV0QueueId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", mux.Vars(r)["id"], &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV0QueueId(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PutApiV0QueueId operation middleware
func (siw *ServerInterfaceWrapper) PutApiV0QueueId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "id", mux.Vars(r)["id"], &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiV0QueueId(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/", wrapper.Get).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/v0", wrapper.GetApiV0).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/v0/graph", wrapper.GetApiV0Graph).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/v0/jobs", wrapper.GetApiV0Jobs).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/v0/jobs/{id}", wrapper.GetApiV0JobsId).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/v0/queue", wrapper.GetApiV0Queue).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/v0/queue", wrapper.PostApiV0Queue).Methods("POST")

	r.HandleFunc(options.BaseURL+"/api/v0/queue/{id}", wrapper.GetApiV0QueueId).Methods("GET")

	r.HandleFunc(options.BaseURL+"/api/v0/queue/{id}", wrapper.PutApiV0QueueId).Methods("PUT")

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZX3PbuBH/Khi0D+2UkmjZPiV6c5NMzte7S5rkrjNNPB2QXIpwQADGH9tKRt+9A4Ci",
	"RBKypThJk+m92BQBLHZ/u/vbBfgR56KWggM3Gs8/Yp1XUBP/CEoJ5R6kEhKUoeBfF2AIZeFJ54pKQwXH",
	"c3yGKlsTPlJACpIxQHArGeHEDSMtIaclzZERyFRUI5HnVingOSBRIlMBkkpkDOoxTjDckloywHP8RFhW",
	"IC4MKikvEEEKSgjLjEAEXYoM5YQxKNA7XIMhBTHkHcYJNkvpBGijKF/gVYINNU7kUG1dCWWSvvba1jVR",
	"y552yFTEoNc/vvjt56fo1xdvUF4RvgBUKlFv22TEbgsTBLc5SINKoZC0SgoN2s1hIieMfvCIdWH4SWQB",
	"BGF5MTRu1b4R2SXkxpnrvecdRg3U/uHPCko8x3+abFw+afw9Cc7eCCJKkaWXcwu5dRq9gisL2gwDIqeF",
	"D5dW24yUywzooliqD+ZUl3Jmi3pW2dkPtpotpz/w8hhKu2RXJCuPRc4W5mp5elpmHwoatU3BlaUKCjx/",
	"6ze7iJi7UERWkWAlhuyNARcFPBG8pIsYEIzy9/eKCJOiDqlEDUMFD5G6FrqNtZe6V0A4CIb79303O0nJ",
	"6aPZ49HJ9HE+OiFkOnr8KJ2NIJumaXZEYHZ6Esuuw+xYZ+p9C5zOv6znRu33Vt0XNLTNma2tL3Zg9MuW",
	"bl2sgBfQg2uaHj0eHaWjo+mbdDafpvPTdHw6/XcMIW2IMg9bb6zuLleWczccm26zmppP37AH4UZcq0kM",
	"wEuRxXAzaikF5aajy1vMNE7w6JWT1CbokLd7ediP2NahERBoTRa9gLGZ5cbOjx6N088QyMOAdAjsFY9B",
	"t2bqDiz1AxnNKfMFqKxd35r9EWtgTtREElNNjJj437HFjmUjRaSirFDAuxGy/f5tIKt9GGqKVxfJ3rOP",
	"cJeQmjS/I1XaVL5rzib/ds5arbYj/77StDsZSqFqYlxwW1pE84BLaw5oBvo1/4Ex9OmEL6z57JpviPQu",
	"Sc2saI57b+yV5Fvk1PhgY9Mdqb/ViQwa1teGGJqj3A9bFfprUSKC3CrXN8Yq/ENDwsk+d0tiiF6K7D87",
	"tjnUgW6fF37NcKNdbBL0GgDlX7cnj4CTa7l3ARVU3WWI47X4gILCiYfoqBLCbA1kQjAgPIQhyPhmu+xs",
	"cBkYGt4fYOlhJsbUubJg4YHFybduX6A6bfI7ZnUXume3BhQnDLXEgc6fdo5ee5WbWP/1nkoJkS3/VYGp",
	"QIVjsPMPuiEaNdNRYf3hsQ0q7c99NTF5RfmicyosCdOQRCNrDcAOY8OE9bE0dCzbZ273EFq9SBdagFJd",
	"OvSWUI20qAE1E+JLhTV3L3UT9jjNrDyBlSJynK8lo+USSZsxmqOzl+e4PfqvB3GCr0HpsCAdp+Mjz1QS",
	"OJEUz/HxOB0f45APHsaJ+7MAr7uLKJ9h566yPwenrwItBdchzKZp6hsawQ2EjtfArZlUpmabC5YuCu9s",
	"mh7nboZ/gvA7E8Uy/P67KJbISQkDk81I82KzNILeKunzxT88ps0NxxZoP7rDpBuaEEkn1+ldZp9J+nt6",
	"v+1EStZQ0uSaF2Mi6d8uteBdKO7K9Gqt1HcD4++pi7sBmpP2jqLBtCvuZ6oNIox5TtCIcp+ca5kbfgpS",
	"kh0eed6MfnG3BDW+Sb+8H/cc8xxMC+SNUO/RRvm1b9aHrahrzjgizfJLkTm+IkhTvmCOs0A6XxEvuGTi",
	"ZozeOFIDXvgjL2JUG+0d6/YY7/TcT06Dr+A4b+n34bc2Jc426OuB2yYfabG6l6ocvOeFZ3VFajCgtD9T",
	"dnX4ldSwVRddKV54iqdu1DdICeak9ldPBd7u+I2ykGzh2Lf34uv49tt1bYJP0pPPbnJzz/0tWt29tR9S",
	"Uvh8kS0RLTpB3TbXO+tE4JM142hEeOFzY101goRdTPPPZvSLh2NQ4/vgmk59aBRPsBQ64oIuwVPtD1ul",
	"UDXSVkqhDBKcLRNE/aALAQW5qGt/s+Qnc6FqwpDVgDLIifu/mUzrAqRwbhij1wDo5W9vUCc2AuP13ftS",
	"6L5//R2Ig+4O196Obm5uRk77kVUMeC6aW+49829w49K9CHG0uBrE2jRSZPMcpIGiYYr0/4kpnjnVUHNl",
	"SPkCNa7rB+kry3uZH475T86for/04uyvQ07Zr1L68ImVysNr4D0Xk1+lJoar0++mTyUcUQN1+KLccvm6",
	"SiQ4egP0jPtZ2n8g95HjOhcVjRYnc0GvgbuoGZKI/d8EwT5MdWC6/0FM3wQxBbEa1PU6hKxieI4neHWx",
	"+m8AAAD//6i9fsB/IgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
