#!/bin/bash

#run_program.sh 'if [ $(file --mime --brief ${input_file} \| grep -c text\/plain) ] \; if python3 /usr/local/bin/bart-summarize.py ${input_file} ${output_dir} \; fi' /inputs /outputs ;


#DEBUG=true run_program.sh 'if [ \$\(file --mime --brief ${input_file} \| grep -c text\/plain\) ] \; then echo 1 \; fi' /inputs /outputs ;
run_program.sh 'if [ \$\(file --mime --brief ${input_file} \| grep -c text\/plain\) -eq 1 ] \; then python3 /usr/local/bin/bart-summarize.py ${input_file} ${output_dir} \; else exit 1 \; fi' /inputs /outputs ;