#!/bin/bash

run_program.sh 'if [ \$\(/usr/local/bin/file5.41 --mime --brief ${input_file} \| grep -c text\/plain \) -eq 1 ] \; then python3 /usr/local/bin/bart-summarize.py ${input_file} ${output_dir} \; fi' /inputs /outputs ;