#!/bin/bash

export VALID_EXTENSIONS=parquet,xlsx,zip,csv

run_program.sh 'echo ${input_file} \&\& frictionless extract --trusted ${input_file} --csv \> ${output_file}.csv' /inputs /outputs ;
echo '{}' ;