#!/bin/bash

# export DEFAULT_FILENAME=file
# export APPEND_EXTENSION=metadata.json
# export DEBUG=true
# From: https://github.com/ultralytics/ultralytics/blob/main/docs/modes/predict.md
export VALID_EXTENSIONS=bmp,dng,jpeg,jpg,mpo,png,tif,tiff,webp,pfm,asf,avi,gif,m4v,mkv,mov,mp4,mpeg,mpg,ts,wmv,webm

run_program.sh 'yolo detect predict cfg=/workspace/config.yaml source="${input_file}" project="${output_dir}"' /inputs /outputs 2>> /outputs/stderr 1>> /outputs/stdout

for src in $(find /outputs -name predict* -type d); do
    dest=${src%/predict*}
    rsync --remove-source-files -a $src/ $dest/
    rm -rf $src
done

# Parse humanised classification names from crops directories
classes=$(find /outputs -path '*/crops/*' -type d | sort | uniq)
for class in $classes; do
    class=$(basename $class)
    echo '{"content-classification": "'$class'"}'
done
