openapi: 3.0.3
info:
  title: Amplify
  version: 0.0.1
  description: Amplify public API
servers:
  - url: /api
paths:
  /v0:
    get:
      summary: Amplify home
      responses:
        '200':
          description: OK
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/home'
            text/html:
              schema:
                type: string
                example: <html><body>Body text</body></html>
  /v0/queue:
    get:
      summary: Amplify work queue
      description: Lists all workflows and jobs in the queue
      responses:
        '200':
          description: Ok.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/queue'
            text/html:
              schema:
                type: string
                example: <html><body>Body text</body></html>
  /v0/queue/{id}:
    get:
      summary: Get an item from the queue by id
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: Ok.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/node'
            text/html:
              schema:
                type: string
                example: <html><body>Body text</body></html>
    put:
      summary: Run all workflows for a CID
      description: Enqueues a request to run all workflows for the given CID
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/executionRequest'
      responses:
        '202':
          description: Accepted.
        '400':
          description: Error submitting request.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/errors'
            text/html:
              schema:
                type: string
                example: <html><body>Body text</body></html>
  /v0/jobs:
    get:
      summary: List all Amplify jobs
      description: An amplify job is a single step in a workflow. This endpoint lists all jobs.
      responses:
        '200':
          description: Ok.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/jobs'
            text/html:
              schema:
                type: string
                example: <html><body>Body text</body></html>
  /v0/jobs/{id}:
    get:
      summary: Get a job by id
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Name of the job to get
      responses:
        '200':
          description: Ok.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/job'
            text/html:
              schema:
                type: string
                example: <html><body>Body text</body></html>
        '404':
          description: Job not found
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/errors'
            text/html:
              schema:
                type: string
                example: <html><body>Body text</body></html>
  /v0/graph:
    get:
      summary: Get Amplify work graph
      description: List all nodes in the Amplify execution graph
      responses:
        '200':
          description: Ok.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/graph'
            text/html:
              schema:
                type: string
                example: <html><body>Body text</body></html>
components:
  schemas:
    home:
      type: object
      properties:
        type:
          type: string
          example: home
        links:
          $ref: '#/components/schemas/links'
    executionRequest:
      type: object
      required: ["cid"]
      properties:
        cid:
          type: string
          example: bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi
    itemMetadata:
      type: object
      required: ["submitted"]
      properties:
        submitted:
          type: string
          example: "2019-10-12T07:20:50.52Z"
        started:
          type: string
          example: "2019-10-12T07:20:50.52Z"
        ended:
          type: string
          example: "2019-10-12T07:20:50.52Z"
    item:
      type: object
      required: ["id", "type", "metadata"]
      properties:
        id:
          type: string
          example: 740a5879-429c-4aa2-9807-eb200b1ae754
        type:
          type: string
          example: item
        links:
          $ref: '#/components/schemas/links'
        metadata:
          $ref: '#/components/schemas/itemMetadata'
    node:
      type: object
      required: ["id", "metadata", "inputs", "outputs", "type"]
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          example: "node"
        metadata:
          $ref: '#/components/schemas/itemMetadata'
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/executionRequest'
        outputs:
          type: array
          items:
            $ref: '#/components/schemas/executionRequest'
        status:
          $ref: '#/components/schemas/status'
        links:
          $ref: '#/components/schemas/links'
        children:
          type: array
          items:
            $ref: '#/components/schemas/node'
          example:
            - id: 740a5879-429c-4aa2-9807-eb200b1ae751
              metadata:
                submitted: "2019-10-12T07:20:50.52Z"
                started: "2019-10-12T07:20:50.52Z"
                ended: "2019-10-12T07:20:50.52Z"
              children:
              - id: 740a5879-429c-4aa2-9807-eb200b1ae752
    status:
      type: object
      properties:
        id:
          type: string
          example: 740a5879-429c-4aa2-9807-eb200b1ae752
          description: External execution ID
        status:
          type: string
          example: Completed
          description: External status of the job
        stdout:
          type: string
          example: this is some stdout
        stderr:
          type: string
          example: this is some stderr
        skipped:
          type: boolean
          example: false
          description: Whether this node was skipped due to predicates not matching.
    queue:  
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/item'
        links:
          $ref: '#/components/schemas/links'
    job:
      type: object
      required: ["id", "image", "type"]
      properties:
        id:
          type: string
          example: metadata
        image:
          type: string
          example: 'ubuntu:18.04'
        entrypoint:
          type: array
          example: ["ls", "-R"]
          items:
            type: string
        type:
          type: string
          example: job
        links:
          $ref: '#/components/schemas/links'
    jobs:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/job'
        links:
          $ref: '#/components/schemas/links'
    nodeConfig:
      type: object
      description: Static configuration of a node.
      properties:
        id:
          type: string
        job_id:
          type: string
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/nodeInput'
        outputs:
          type: array
          items:
            $ref: '#/components/schemas/nodeOutput'
    nodeInput:
      type: object
      description: Input specification for a node.
      properties:
        root:
          type: boolean
        step_id:
          type: string
        output_id:
          type: string
        path:
          type: string
        predicate:
          type: string
    nodeOutput:
      type: object
      description: Output specification for a node.
      properties:
        id:
          type: string
        path:
          type: string
    graph:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/nodeConfig'
        links:
          $ref: '#/components/schemas/links'
    links:
      type: object
      example: 
        self: /path/to/self
    errors:
      type: array
      items:
        $ref: '#/components/schemas/error'
    error:
      type: object
      properties:
        title:
          type: string
          description: A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
          example: Job not found
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
          example: Could not find a reference to a job called "metadata"